name: CI
on:
  push:
    branches: [main, mercuryScribe0.1]
  pull_request:
    branches: [main, mercuryScribe0.1]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run unit tests
        env:
          SKIP_PREFLIGHT_CHECKS: "1"
        run: pytest -q -k 'not integration'
