name: CI
on:
  push:
    branches: [main, mercuryScribe0.1]
  pull_request:
    branches: [main, mercuryScribe0.1]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run unit tests
        env:
          SKIP_PREFLIGHT_CHECKS: "1"
        run: pytest -q -k 'not integration'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          # Run flake8 on the package and top-level scripts. Adjust patterns as needed.
          flake8 transcribe_with_whisper || true

  packaging-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build sdist and wheel (no isolation)
        run: |
          # Use --no-isolation so the build runs in the runner environment and does not
          # attempt to install large runtime deps. This is a smoke check for packaging.
          python -m build --sdist --wheel --no-isolation
