name: Build and Publish Docker Images (Multi-arch)

on:
  workflow_dispatch: {}
  push:
    tags: ["v*"]

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: web
            file: Dockerfile
            suffix: web
          - name: cli
            file: Dockerfile.cli
            suffix: cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image name
        id: img
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "image=ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-${{ matrix.suffix }}" >> $GITHUB_OUTPUT

      - name: Show image details
        run: |
          echo "Image: ${{ steps.img.outputs.image }}"
          echo "Dockerfile: ${{ matrix.file }}"

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.img.outputs.image }}:latest
            ${{ steps.img.outputs.image }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
