---
name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # e.g., v0.1.1
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Set to true to publish to PyPI when running manually'
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      # No credentials necessary: https://pypi.org/manage/project/transcribe-with-whisper/settings/publishing/
      - name: Publish to PyPI
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
          (github.event_name == 'release' && github.event.action == 'published') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # If a package file with the same filename+hash already exists on PyPI,
          # don't fail the workflow. This avoids a hard failure when a tag push
          # and a release publish both trigger the publish step for the same
          # distribution.
          skip-existing: true
