---
name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # e.g., v0.1.1
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      # No credentials necessary: https://pypi.org/manage/project/transcribe-with-whisper/settings/publishing/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
